<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>DreamLand__3_-removebg-preview.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="DreamLand__3_-removebg-preview.ico" />
  </ItemGroup>

</Project>
